hadoop_home: /opt/hadoop-2.X
mirrors: [ "http://xenia.sote.hu/ftp/mirrors/www.apache.org/hadoop/common/hadoop-2.6.0", "http://ftp.itu.edu.tr/Mirror/Apache/hadoop/common/hadoop-2.6.0" ]

hadoop_master:
  host_ip: "{{hostvars['master']['ansible_host']}}"
  host_name: "{{hostvars['master']['ansible_hostname']}}"

hadoop_slaves:
   - host_ip: "{{hostvars['slave01']['ansible_host']}}"
     host_name: "{{hostvars['slave01']['ansible_hostname']}}"
   - host_ip: "{{hostvars['slave02']['ansible_host']}}"
     host_name: "{{hostvars['slave02']['ansible_hostname']}}"

namenode_dir: "/opt/hdfs/namenode"
datanode_dir: "/opt/hdfs/datanode"
