---

- name: Copy the files to the master
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    mode: 744
  with_fileglob:
    - roles/install_hadoop/files/*

- name: Put the text file to HDFS
  command: "{{ hadoop_home }}/bin/hdfs dfs -put -f count_of_monte_cristo.txt /"

- name: Run the job
  command: >
           {{ hadoop_home }}/bin/hadoop jar {{ hadoop_home }}/share/hadoop/tools/lib/hadoop-streaming-2.6.0.jar
           -file word_mapper.py -mapper word_mapper.py
           -file word_reduce.py -reducer word_reduce.py
           -input /count_of_monte_cristo.txt
           -output output_wordcount

- name: Clean output directory
  command: "rm -rf /root/output/*"

- name: Copy the output from HDFS file to local file system
  command: "{{ hadoop_home }}/bin/hdfs dfs -copyToLocal ./output_wordcount/part-00000 ./output/output"



