---
- name: Create ssh keys
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa


- name: Fetch the ssh keys
  fetch:
    src: "/root/.ssh/id_rsa.pub"
    dest: "/var/tmp/temp-{{ ansible_hostname }}"
    flat: yes


- name: Copy the ssh keys
  lineinfile:
    dest: "/root/.ssh/authorized_keys"
    insertafter: EOF
    line: "{{item}}"
    state: present
  with_items:
    - "{{ lookup('file', '/var/tmp/temp-{{master_hostname}}') }}"
    - "{{ lookup('file', '/var/tmp/temp-{{slaves_hostnames[0]}}') }}"
    - "{{ lookup('file', '/var/tmp/temp-{{slaves_hostnames[1]}}') }}"
  no_log: True


- name: Create /etc/hosts file
  template:
    src: hosts.j2
    dest: "/etc/hosts"
    owner: root
    group: root


- name: Create ssh config on master
  template:
    src: config.j2
    dest: "/root/.ssh/config"
    owner: root
    group: root