---
- name: Create droplet
  digital_ocean:
    state: present
    command: droplet
    ssh_key_ids: "{{ ssh_key_id }}"
    name: "{{ item  }}"
    unique_name: yes
    api_token: "{{ api_token }}"
    size_id: "{{ size }}"
    region_id: "{{ region }}"
    image_id: "{{ image }}"
  with_items: "{{ list_of_servers }}"
  register: "droplets"

- name: Add instance to local host group
  lineinfile:
    dest: "{{ inventory_file }}"
    regexp: "{{ item.droplet.name }}"
    line:  "{{ item.droplet.name }} ansible_host={{ item.droplet.ip_address }}"
    state: present
  with_items:
    - "{{ droplets.results }}"

- name: Wait for port 22 to be ready
  wait_for:
    port: 22
    host: "{{droplets.results[-1].droplet.ip_address}}"
    delay: 5

- meta: refresh_inventory
